# Set some default verbose
#/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/echo "**********************************************************************"
/control/echo "****** Calling vis.mac *******"
/control/echo "**********************************************************************"
/control/execute vis.mac
