/control/execute commands.mac

/run/initialize

# only with 10.6.x: /process/had/verbose 0
/control/verbose 0
/run/verbose 0

# Use this open statement to create an OpenGL view:
/vis/open OGL 1000x1000-0+0


/vis/viewer/set/autoRefresh true
/vis/verbose errors

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 115. 160.

# Specify zoom value:
/vis/viewer/zoom 1.4

# Specify style (surface or wireframe):
/vis/viewer/set/style surface
/vis/viewer/set/style wireframe

/vis/viewer/set/hiddenEdge 0
/vis/viewer/set/autoRefresh true

/vis/viewer/set/globalLineWidthScale 2

# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 30 cm

# Draw smooth trajectories at end of event, showing trajectory points
/vis/scene/add/eventID
/vis/scene/add/trajectories smooth
/vis/scene/add/trajectories rich

#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
#/vis/modeling/trajectories/drawByCharge-0/set 1 red
#/vis/modeling/trajectories/drawByCharge-0/set -1 blue
#/vis/modeling/trajectories/drawByCharge-0/set 0 white

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- cyan
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/modeling/trajectories/drawByParticleID-0/set gamma white
/vis/modeling/trajectories/drawByParticleID-0/setRGBA nu_e 0.8 0.6 0.8 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_nu_e 0.8 0.6 0.8 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA nu_mu 0.6 0.8 0.8 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_nu_mu 0.6 0.8 0.8 1
/vis/modeling/trajectories/drawByParticleID-0/set neutron gray
/vis/modeling/trajectories/drawByParticleID-0/set Mu yellow

/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2


#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

# Draw hits at end of event:
/vis/scene/add/hits

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

/vis/verbose warnings

# ----------------------------------------------------------------------
# -- physics setup (from run.mac)
/tracking/verbose 0


/tracking/storeTrajectory 2


#/macs0/det/setField 4 tesla
/macs0/field/value -0.0048 tesla

# -- (signal) Muonium source and decay
#/gun/position 0 0 0 cm
#/gun/energy 0.026 eV
#/gun/direction 0 0 1

# -- test hits with e- as a background source
#/gun/particle e-
#/gun/position 0 0 -70 cm
#/gun/energy 2 MeV
#/gun/direction 0 0 1

# -- turn on internal conversion
/particle/select mu+
/particle/property/decay/select 2
/particle/property/decay/br 1

/gun/particle mu+
/gun/position 0 0 50 cm
/gun/energy 2 eV
/gun/direction 0 0 1

/run/beamOn 1
